### ISSUE TITLE
Compile error on 4.14 and v4.1.8_9499 branch after change

### ISSUE THREAD

**Issue by noah95** [lwfinger/rtl8188eu#295] opened 2019-10-07 08:58 UTC
The change added in 5f2c143 crashes my build with an error of 
```
drivers/net/wireless/realtek/rtl8188eu/os_dep/ioctl_cfg80211.c:2951:3: error: implicit declaration of function ‘cfg80211_sinfo_alloc_tid_stats’; did you mean ‘cfg80211_inform_bss_width’? [-Werror=implicit-function-declaration]
   cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
```
not found. Using a linux-4.14.101.tar.xz vanilla kernel.

Sorry i don't have profound knowledge on drivers yet, I just reverted this commit and then my build succeeds.

**Comment by lwfinger** [comment] 2019-10-08 18:44
The problem is now fixed. The missing routine was added in kernel 4.18, but it was not protected against older kernels. You can do a 'git pull' and all will be well.

**Closed** 2019-10-09 16:44 UTC
